# Generated by Django 4.1.7 on 2023-04-10 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universeMain', '0002_attendee_tag_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='numberAttendees',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
