# Generated by Django 4.1.4 on 2023-05-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universeMain",
            "0003_alter_event_attendees_alter_event_numberattendees_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="numberAttendees",
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="eventTime",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="maxAttendees",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="eventDate",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
