# Generated by Django 4.1.4 on 2023-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universeMain", "0005_studentuser_remove_event_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentuser",
            name="email",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="studentuser",
            name="password",
            field=models.CharField(default="", max_length=30),
        ),
    ]
